### PR TITLE
0.1.14/front end refactor

### PR DESCRIPTION
**Pull request by ArnoldasSid**
New folder structure in carpool-view-flow. Fixed almost all Eslint errors in carpool-view-flow. Other minor refactoring

### CODE REVIEW

**Comment by spastai** [comment]
Test is failing.

For some reason Scenario: Dick enters trip, Ron - recurrent matching and Dick gets notification
is using less reliable step "And I enter:" : 
https://travis-ci.org/vilnius/vilnius-carpool/builds/144569278#L1279

while https://github.com/ArnoldasSid/vilnius-carpool/blob/0.1.14/front-end-refactor/src/tests/cucumber/features/uc8-post-trip.feature#L39 
is using correct one 

Strange.

**Comment by spastai** [comment]
What is the purpose of https://github.com/ArnoldasSid/vilnius-carpool/blob/879d83f4940506d8f78f58c1d4f1cf532699335b/src/packages/carpool-view-flow/react/components/ride-info/RideInfoWithMap.jsx ?
Please add comments. 

The problem is that GoogleMap differs depending on context (it should show some view for rider, the other for driver, RideRequest, DriveConfirm screens).
The same applies for RideInfo - i.e. #177 should implement different view for rider.

Now I'm trying to implement general GoogleMaps, just parametrizing it, but not sure this will work for RideInfo. Please reply here

**Comment by spastai** [comment]
Isn't so that RideInfoWithMap.jsx to solve view problems (Fit Map and Info into screen)?
That would be huge huge drawback of not using responsive libraries.
View and logic separation is a mandatory paradigm to keep code clear.
Now it's seems that our code structure is formed by representation demands.

**Comment by ArnoldasSid** [comment]
The problem I was trying to solve was that 4 screens: YourDrive, YourRide, RideRequest, DriveConfirm have a very similar layout: GoogleMap, RideInfo, and some buttons. Given that there are 4 screens that need GoogleMap and RideInfo displayed in the same way, I think it is a good idea to create a component which helps to layout these two components in 4 given screens. The goal is code reuse (DRY). (It all did start with things not fitting into screen and me writing code so it does, then copy-pasting it to second screen so it does fit too, but forgetting to copy paste it to third screen and now seeing that it doesn't fit into screen).

Currently RideInfo and GoogleMap components take ride and drive props and render accordingly, so RideInfoWithMap also takes those props and passes them through to both components after laying them out correctly.

**Pull request merged**
